Repository sorcerers-apprentices/chess, pull requests merged in 2025-09, with the labels that each got.

#19 Basic UI
  apps/chess/eslint.config.js
  apps/chess/project.json
  apps/chess/public/assets/img/not-found.svg
  apps/chess/public/assets/img/sidebar-item.svg
  apps/chess/src/app/app.html
  apps/chess/src/app/app.routes.ts
  apps/chess/src/app/app.scss
  apps/chess/src/app/app.ts
  apps/chess/src/app/components/header/header.html
  apps/chess/src/app/components/header/header.scss
  apps/chess/src/app/components/header/header.ts
  apps/chess/src/app/components/navigation/navigation.html
  apps/chess/src/app/components/navigation/navigation.scss
  apps/chess/src/app/components/navigation/navigation.ts
  apps/chess/src/app/components/sidebar/sidebar.html
  apps/chess/src/app/components/sidebar/sidebar.scss
  apps/chess/src/app/components/sidebar/sidebar.ts
  apps/chess/src/app/pages/game-page/game-page.html
  apps/chess/src/app/pages/game-page/game-page.ts
  apps/chess/src/app/pages/not-found-page/not-found-page.html
  apps/chess/src/app/pages/not-found-page/not-found-page.scss
  apps/chess/src/app/pages/not-found-page/not-found-page.ts
Labels: enhancement

#35 Add chess board
  .lintstagedrc.json
  src/app/components/chess-board/chess-board.html
  src/app/components/chess-board/chess-board.scss
  src/app/components/chess-board/chess-board.ts
  src/app/components/chess-square/chess-square.html
  src/app/components/chess-square/chess-square.scss
  src/app/components/chess-square/chess-square.ts
  src/app/constants/chess-square.constans.ts
  src/app/pages/game-page/game-page.html
  src/app/pages/game-page/game-page.ts
  src/app/types/chess-square.type.ts
Labels: enhancement

#48 Add panel game setting
  angular.json
  src/app/components/chess-board/chess-board.scss
  src/app/components/game-settings/game-settings.html
  src/app/components/game-settings/game-settings.scss
  src/app/components/game-settings/game-settings.ts
  src/app/pages/game-page/game-page.html
  src/app/pages/game-page/game-page.scss
  src/app/pages/game-page/game-page.ts
  src/app/styles/variables.scss
Labels: enhancement

#51 Add player panel
  src/app/components/chess-board/chess-board.html
  src/app/components/chess-board/chess-board.ts
  src/app/components/player-panel/player-panel.html
  src/app/components/player-panel/player-panel.scss
  src/app/components/player-panel/player-panel.ts
  src/app/constants/chess-piece.constans.ts
  src/app/pages/game-page/game-page.html
  src/app/pages/game-page/game-page.scss
  src/app/pages/game-page/game-page.ts
  src/app/services/board-setup.service.ts
  src/app/types/chess-square.type.ts
Labels: enhancement

#52 Add adaptive game board
  src/app/components/chess-board/chess-board.scss
  src/app/components/game-settings/game-settings.scss
  src/app/components/player-panel/player-panel.html
  src/app/components/player-panel/player-panel.scss
  src/app/components/player-panel/player-panel.ts
  src/app/pages/game-page/game-page.scss
  src/app/styles/variables.scss
Labels: bug

#54 Change color dark theme
  src/app/constants/chess-square.constans.ts
  src/app/pages/game-page/game-page.scss
  src/app/types/chess-square.type.ts
Labels: bug

#64 Add function for supabase, add home-page, fix sidebar
  public/assets/i18n/en.json
  public/assets/i18n/ru.json
  src/app/app.config.ts
  src/app/app.routes.ts
  src/app/components/header/header.html
  src/app/components/header/header.ts
  src/app/components/sidebar/sidebar.html
  src/app/components/sidebar/sidebar.ts
  src/app/pages/game-page/game-page.ts
  src/app/pages/home-page/home-page.html
  src/app/pages/home-page/home-page.scss
  src/app/pages/home-page/home-page.ts
  src/app/pages/sign-in-page/sign-in-page.ts
  src/app/pages/sign-up-page/sign-up-page.html
  src/app/pages/sign-up-page/sign-up-page.scss
  src/app/pages/sign-up-page/sign-up-page.ts
  src/app/services/auth.service.ts
  src/app/services/game-supabase.service.ts
  src/app/services/language.service.ts
  src/app/services/user-supabase.service.ts
Labels: bug, enhancement

#75 fix horizontal scroll and translate confirmation
  public/assets/i18n/en.json
  public/assets/i18n/ru.json
  src/app/guards/auth.guard.ts
  src/app/pages/sign-in-page/sign-in-page.scss
Labels: bug

#79 ELO calculation logic
  src/app/constants/elo.constants.ts
  src/app/services/elo.service.ts
  src/app/services/game.service.ts
  src/app/store/actions/user.actions.ts
  src/app/store/reducers/user.reducer.ts
  src/app/store/selectors/game.selectors.ts
  src/app/store/selectors/user.selectors.ts
  src/app/store/states/user.state.ts
Labels: enhancement

#81 Moves chess pieces
  src/app/components/chess-board/chess-board.html
  src/app/components/chess-board/chess-board.ts
  src/app/components/chess-square/chess-square.ts
  src/app/constants/chess-game.constants.ts
  src/app/constants/chess-piece.constans.ts
  src/app/pages/game-page/game-page.html
  src/app/pages/game-page/game-page.ts
  src/app/pages/home-page/home-page.ts
  src/app/services/board-setup.service.ts
  src/app/services/board-state.service.ts
  src/app/services/game.service.ts
  src/app/store/actions/game.actions.ts
  src/app/store/reducers/game.reducers.ts
  src/app/types/chess-square.type.ts
  src/app/types/drag-drop-data.type.ts
Labels: enhancement

#82 Fixed build
  src/app/services/game.service.ts
  src/app/store/reducers/game.reducers.ts
Labels: bug

#84 Remove the horizontal scroll Sign In
  src/app/components/header/header.scss
  src/app/pages/sign-in-page/sign-in-page.scss
  src/app/pages/sign-up-page/sign-up-page.scss
  src/app/styles/base.scss
Labels: bug

#95 fix: fix deploy
  src/app/services/auth.service.ts
Labels: bug

#97 Game timer
  src/app/components/game-settings/game-settings.html
  src/app/components/game-settings/game-settings.ts
  src/app/services/player-timer.service.ts
Labels: enhancement

#99 Add a chess move undo/redo
  src/app/components/game-settings/game-settings.html
  src/app/components/game-settings/game-settings.ts
  src/app/pages/home-page/home-page.ts
  src/app/services/board-setup.service.ts
  src/app/services/elo.service.ts
  src/app/services/game-supabase.service.ts
  src/app/services/game.service.ts
  src/app/services/opponent-runner.service.ts
  src/app/services/player-timer.service.ts
  src/app/store/actions/game.actions.ts
  src/app/store/effects/game.effects.ts
  src/app/store/reducers/game.reducers.ts
  src/app/store/selectors/game.selectors.ts
  src/app/store/states/game.state.ts
  src/app/types/supabase-game.type.ts
Labels: enhancement

#102 Add resignation of the game
  src/app/components/game-settings/game-settings.scss
  src/app/pages/game-page/game-page.html
  src/app/pages/game-page/game-page.ts
  src/app/pages/home-page/home-page.scss
  src/app/services/game.service.ts
  src/app/store/reducers/game.reducers.ts
  src/app/styles/base.scss
Labels: enhancement

#105 Add timer save and delete flip the chessboard
  src/app/components/chess-board/chess-board.ts
  src/app/components/game-settings/game-settings.html
  src/app/components/game-settings/game-settings.scss
  src/app/pages/game-page/game-page.scss
  src/app/services/player-timer.service.ts
  stylelint.config.js
Labels: enhancement

#116 fix: fix reload game settings
  src/app/pages/home-page/home-page.ts
Labels: bug

#117 Docs Refactor
  .github/workflows/main.yml
  README.md
  public/assets/i18n/ru.json
  src/app/pages/sign-in-page/sign-in-page.html
  src/app/pages/sign-up-page/sign-up-page.html
Labels: documentation, refactor

#119 Docs Refactor
  README.md
  public/assets/img/docs/4444.png
  public/assets/img/docs/img.png
  public/assets/img/docs/img_1.png
  public/assets/img/docs/img_2.png
  public/assets/img/docs/img_3.png
  public/assets/img/docs/img_4.png
  public/assets/img/docs/img_5.png
Labels: documentation, refactor
