Repository sorcerers-apprentices/chess, pull requests merged in 2025-10, with the labels that each got.

#123 Add translation for modal
  public/assets/i18n/en.json
  public/assets/i18n/ru.json
  src/app/pages/game-page/game-page.html
Labels: enhancement

#124 Fix bugs
  src/app/components/game-settings/game-settings.html
  src/app/components/game-settings/game-settings.scss
  src/app/components/sidebar/sidebar.ts
  src/app/services/language.service.spec.ts
  src/app/services/language.service.ts
  src/app/styles/base.scss
  tsconfig.json
Labels: bug

#128 Jest test
  jest.config.ts
  src/app/components/sidebar/sidebar.spec.ts
  src/app/guards/auth.guards.spec.ts
  src/app/services/elo.service.spec.ts
  src/app/services/game.service.ts
  src/app/services/leave-bypass.service.spec.ts
  src/app/services/timer-storage.service.spec.ts
Labels: bug, enhancement
